version: '3'

services:
  postgres:
    image: postgres
    volumes:
    - postgres_data:/var/lib/postgresql/data
    environment:
    - POSTGRES_DATABASE=proflab_db
    - POSTGRES_USER=proflab_user
    - POSTGRES_PASSWORD=puacX9KK[@mX
    ports:
      - 5432:5432
    restart: always

  flask_proflab_app:
    build: ./service_for_proflab
    depends_on:
      - postgres
    container_name: proflab
    ports:
      - 5000:5000
    environment:
      API_KEY: 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
      DB_HOST: localhost
      DB_PORT: 5432
      DB_USER: proflab_user
      DB_PASSWORD: puacX9KK[@mX
      DB_NAME: proflab_db
      
    restart: always

volumes: 
  postgres_data: